### PR TITLE
Fix build fail when rebuilding extensions.

### PR DESCRIPTION
**Pull request by shreyashsaitwal**
Fixed the issue which caused the build to fail when rebuilding the extensions. This PR solves issue #1

### CODE REVIEW

**Comment by ewpatton** [comment]
@ShreyashSaitwal Did the other fix I pushed work appropriate so we no longer need to clean on every build?

**Comment by shreyashsaitwal** [comment]
No, it doesn't work. I still get the same error when I try to rebuild.

**Comment by ewpatton** [comment]
@ShreyashSaitwal Are you on Windows? I don't see this issue on macOS.

**Comment by shreyashsaitwal** [comment]
Yes, I'm using Windows 10.

**Comment by shreyashsaitwal** [comment]
Oh, it seems like there was something wrong on my end. I tried cloning the latest version of the repo and its working now. Sorry for any inconvenience I might have caused.

**Comment by ewpatton** [comment]
@ShreyashSaitwal No problem. Glad we were able to get it working for you.

**Pull request closed without merging**
